Added a Readme and actions
projecttacoma/bulk-data-utilities pull request #12
Opened 2021-12-06 19:27 UTC by MegRiley

Files changed:

- readme.md - added some more details and filled in a basic/barebones readme for this project
- ci.yml - added a basic work flow that runs npm check on pull request

2021-12-08 16:04 UTC, mgramigna requested changes

2021-12-08 16:04 UTC, mgramigna commented on README.md
> +A library to handle  bulk import requests and interact with the [DEQM-Test-Server](https://github.com/projecttacoma/deqm-test-server)
I'd link to the import ping and pull spec somewhere in here:

https://github.com/smart-on-fhir/bulk-import/blob/master/import-pnp.md

2021-12-08 18:01 UTC, MegRiley commented on README.md
> +- [SQLite3](https://www.sqlite.org/download.html)
I wasn't sure, I know I had to install it but my machine is wonky, I'll remove the note.

2021-12-10 14:08 UTC, mgramigna requested changes

2021-12-10 14:08 UTC, mgramigna commented on README.md
> +A library to handle  bulk import requests and interact with the [DEQM-Test-Server](https://github.com/projecttacoma/deqm-test-server) This library is used to help implement bulk import via a  ping an
```suggestion
A library to handle  bulk import requests and interact with the [DEQM-Test-Server](https://github.com/projecttacoma/deqm-test-server) This library is used to help implement bulk import via a  ping and pull approach which is described [here](https://github.com/smart-on-fhir/bulk-import/blob/master/import-pnp.md)
```

space between the link wasn't rendering properly

2021-12-10 14:21 UTC, mgramigna approved these changes

2021-12-10 14:21 UTC, merged